import type { Metadata } from "next";
import { Concert_One, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/ui/Header";
import Footer from "@/ui/Footer";
import { Analytics } from "@vercel/analytics/next";
import clientEnv from "@/utils/clientEnv";
import AdsterraPopunder from "@/components/AdsterraPopunder";

const concertOne = Concert_One({
  variable: "--font-concert-one",
  weight: "400",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${concertOne.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
        {clientEnv.NEXT_PUBLIC_NODE_ENV === "production" && <Analytics />}
        <AdsterraPopunder />
      </body>
    </html>
  );
}
