import z from "zod";

const clientEnv = z.object({
  NEXT_PUBLIC_URL: z.url(),
  NEXT_PUBLIC_NODE_ENV: z.enum(["production", "development"]),
  NEXT_PUBLIC_ADSTERRA_BANNER_728X90_API_KEY: z.string().min(1),
  NEXT_PUBLIC_ADSTERRA_BANNER_468X60_API_KEY: z.string().min(1),
  NEXT_PUBLIC_ADSTERRA_BANNER_320X50_API_KEY: z.string().min(1),
});

export default clientEnv.parse({
  NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
  NEXT_PUBLIC_NODE_ENV: process.env.NEXT_PUBLIC_NODE_ENV,
  NEXT_PUBLIC_ADSTERRA_BANNER_728X90_API_KEY:
    process.env.NEXT_PUBLIC_ADSTERRA_BANNER_728X90_API_KEY,
  NEXT_PUBLIC_ADSTERRA_BANNER_468X60_API_KEY:
    process.env.NEXT_PUBLIC_ADSTERRA_BANNER_468X60_API_KEY,
  NEXT_PUBLIC_ADSTERRA_BANNER_320X50_API_KEY:
    process.env.NEXT_PUBLIC_ADSTERRA_BANNER_320X50_API_KEY,
});
